update cyclictest-server-start to use the same stress-ng launch logic as oslat-server-start

diff --git a/cyclictest-server-start b/cyclictest-server-start
--- a/cyclictest-server-start
+++ b/cyclictest-server-start
@@ -5,6 +5,31 @@ exec 2>&1
 
 . /usr/bin/cyclictest-base || (echo "/usr/bin/cyclictest-base not found"; exit 1)
 
+STRESS_NG_TILES_PER_CPU=1
+
+opts=$(getopt -q -o "" --longoptions "stress-ng-tiles-per-cpu:" -n "getopt.sh" -- "$@");
+if [ $? -ne 0 ]; then
+    printf -- "\tUnrecognized option specified\n\n"
+    exit 1
+fi
+eval set -- "$opts";
+while true; do
+    case "$1" in
+	--stress-ng-tiles-per-cpu)
+	    shift;
+	    STRESS_NG_TILES_PER_CPU=$1
+	    shift;
+	    ;;
+        --)
+            shift;
+            break
+            ;;
+        *)
+            echo "Invalid option: $1"
+            exit 1
+    esac
+done
+
 if [ -z "$WORKLOAD_CPUS" -a -z "$HK_CPUS" ]; then
     TMP_CPUS=$(grep Cpus_allowed_list /proc/self/status | awk '{ print $2 }')
     echo "CPUs Allowed List: ${TMP_CPUS}"
@@ -29,33 +54,32 @@ else
     CPUS="${HK_CPUS},${WORKLOAD_CPUS}"
 fi
 
+echo "STRESS_NG_TILES_PER_CPU=${STRESS_NG_TILES_PER_CPU}"
 echo "CPUS: ${CPUS}"
 
 NUM_CPUS=$(echo "${CPUS}" | sed -e "s/,/ /g" | wc -w)
 echo "NUM_CPUS=${NUM_CPUS}"
+TEST_TILES=$(( ${NUM_CPUS} * ${STRESS_NG_TILES_PER_CPU} ))
+echo "TEST_TILES: ${TEST_TILES}"
 
-NUM_TESTS=9
-TEST_COPIES=1
-if [ ${NUM_CPUS} -gt ${NUM_TESTS} ]; then
-    while [ $(( NUM_TESTS*TEST_COPIES )) -lt ${NUM_CPUS} ]; do
-        (( TEST_COPIES += 1 ))
-    done
-fi
+CMD="taskset -c ${CPUS}"
+CMD+=" stress-ng"
+CMD+=" --cpu ${TEST_TILES}"
+CMD+=" --hdd ${TEST_TILES}"
+CMD+=" --io ${TEST_TILES}"
+CMD+=" --malloc ${TEST_TILES}"
+CMD+=" --mmap ${TEST_TILES}"
+CMD+=" --msg ${TEST_TILES}"
+CMD+=" --stream ${TEST_TILES}"
+CMD+=" --sysinfo ${TEST_TILES}"
+CMD+=" --vm ${TEST_TILES}"
+CMD+=" --timeout 0"
+CMD+=" --metrics"
+CMD+=" --times"
+CMD+=" --verbose"
 
-echo "TEST_COPIES: ${TEST_COPIES}"
-
-taskset -c ${CPUS} \
-        stress-ng \
-        --cpu ${TEST_COPIES} \
-        --hdd ${TEST_COPIES} \
-        --io ${TEST_COPIES} \
-        --malloc ${TEST_COPIES} \
-        --mmap ${TEST_COPIES} \
-        --msg ${TEST_COPIES} \
-        --stream ${TEST_COPIES} \
-        --sysinfo ${TEST_COPIES} \
-        --vm ${TEST_COPIES} \
-        --timeout 0 --metrics --times --verbose > stress-ng.out 2>&1 &
+echo "About to run: ${CMD}"
+${CMD} > stress-ng.out 2>&1 &
 pid=$!
 echo "stress-ng PID is ${pid}"
 echo ${pid} > stress-ng.pid
